In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5]

In [4]:
array = np.array(my_list)

In [5]:
array[2:]

array([3, 4, 5])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
np.linspace(0,11,20)

array([ 0.        ,  0.57894737,  1.15789474,  1.73684211,  2.31578947,
        2.89473684,  3.47368421,  4.05263158,  4.63157895,  5.21052632,
        5.78947368,  6.36842105,  6.94736842,  7.52631579,  8.10526316,
        8.68421053,  9.26315789,  9.84210526, 10.42105263, 11.        ])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(5)

array([0.82135382, 0.09147265, 0.72975969, 0.51431263, 0.32888817])

In [20]:
np.random.rand(5,5)

array([[0.27543686, 0.78084615, 0.61702955, 0.10932036, 0.70574563],
       [0.67274655, 0.34874188, 0.85400432, 0.67175127, 0.34491634],
       [0.61287874, 0.80439736, 0.02810891, 0.29799869, 0.35172086],
       [0.32030464, 0.19453146, 0.82183757, 0.25125673, 0.66480852],
       [0.52924699, 0.74477474, 0.98677139, 0.61946513, 0.96790936]])

In [24]:
rand_arr = np.random.randint(0,100,10)

In [22]:
arr = np.arange(25)

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:

rand_arr.max()

92

In [26]:
rand_arr.min()

1

In [27]:
rand_arr.argmax()

4

In [28]:
rand_arr.argmin()

8